export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "first_name",
    numeric: false,
    label: "First name",
  },
  {
    id: "last_name",
    numeric: false,
    label: "Last name",
  },
  {
    id: "email",
    numeric: false,
    label: "E-mail",
  },
  {
    id: "mobile",
    numeric: false,
    label: "Mobile",
  },
  {
    id: "role",
    numeric: false,
    label: "Role",
  },
  {
    id: "action",
    numeric: true,
    label: "ACTION",
  },
];

export const TableData = [
  {
    first_name: "ABC",
    last_name: "left",
    email: "description",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "111",
  },
  {
    first_name: "dd",
    last_name: "left",
    email: "eeee",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "987",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "222",
  },
  {
    first_name: "Foo",
    last_name: "left",
    email: "baz",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "333",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "444",
  },
  {
    first_name: "Foo",
    last_name: "left",
    email: "baz",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "555",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "666",
  },
  {
    first_name: "Foo",
    last_name: "left",
    email: "baz",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "777",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "888",
  },
  {
    first_name: "Foo",
    last_name: "left",
    email: "baz",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "999",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "101010",
  },
  {
    first_name: "Foo",
    last_name: "left",
    email: "baz",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "111111",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "121212",
  },
  {
    first_name: "Foo",
    last_name: "left",
    email: "baz",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "131313",
  },
  {
    first_name: "Lorem",
    last_name: "left",
    email: "dolor",
    mobile: "metaDescmetaDesc",
    role: "employee",
    _id: "141414",
  },
];
