export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "name",
    numeric: false,
    label: "Name",
  },
  {
    id: "rating",
    numeric: true,
    label: "Rating",
  },
  {
    id: "message",
    numeric: false,
    label: "Message",
  },
  {
    id: "action",
    numeric: true,
    label: "ACTION",
  },
];

export const TableData = [
  {
    name: "ABC",
    status: "Completed",
    rating: "3",
    message: "texts",
    _id: "111",
  },
  {
    name: "dd",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "987",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "222",
  },
  {
    name: "Foo",
    status: "Completed",
    rating: "2",
    message: "texts",
    _id: "333",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "444",
  },
  {
    name: "Foo",
    status: "Completed",
    rating: "2",
    message: "texts",
    _id: "555",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "666",
  },
  {
    name: "Foo",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "777",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "0",
    message: "texts",
    _id: "888",
  },
  {
    name: "Foo",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "999",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "101010",
  },
  {
    name: "Foo",
    status: "Completed",
    rating: "4",
    message: "texts",
    _id: "111111",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "121212",
  },
  {
    name: "Foo",
    status: "Completed",
    rating: "3",
    message: "texts",
    _id: "131313",
  },
  {
    name: "Lorem",
    status: "Completed",
    rating: "5",
    message: "texts",
    _id: "141414",
  },
];
