export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "Name",
    numeric: false,
    label: "Name",
  },
  {
    id: "description",
    numeric: false,
    label: "DESCRIPTION",
  },
  {
    id: "metaTitle",
    numeric: false,
    label: "Meta title",
  },
  {
    id: "metaDesc",
    numeric: false,
    label: "Meta Description",
  },
  {
    id: "action",
    numeric: true,
    label: "ACTION",
  },
];

export const TableData = [
  {
    name: "ABC",
    description: "description",
    metaTitle: "description",
    metaDesc: "metaDescmetaDesc",
    _id: "111",
  },
  {
    name: "dd",
    description: "eeee",
    metaTitle: "eeee",
    metaDesc: "metaDescmetaDesc",
    _id: "987",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "222",
  },
  {
    name: "Foo",
    description: "bar",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "333",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "444",
  },
  {
    name: "Foo",
    description: "bar",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "555",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "666",
  },
  {
    name: "Foo",
    description: "bar",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "777",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "888",
  },
  {
    name: "Foo",
    description: "bar",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "999",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "101010",
  },
  {
    name: "Foo",
    description: "bar",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "111111",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "121212",
  },
  {
    name: "Foo",
    description: "bar",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "131313",
  },
  {
    name: "Lorem",
    description: "ipsum",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "141414",
  },
];
