import { IoCheckmarkDoneOutline } from "react-icons/io5";

export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "name",
    numeric: false,
    label: "Name",
  },
  {
    id: "email",
    numeric: false,
    label: "Email",
  },
  {
    id: "phone",
    numeric: false,
    label: "Phone",
  },
  {
    id: "subject",
    numeric: false,
    label: "Subject",
  },
  {
    id: "message",
    numeric: false,
    label: "Message",
  },
  {
    id: "status",
    numeric: false,
    label: "Status",
  },
  {
    id: "action",
    numeric: false,
    label: "Action",
  },
];

export const TableData = [
  {
    name: "ABC",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "description",
    email: "metaDescmetaDesc",
    _id: "111",
  },
  {
    name: "dd",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "eeee",
    email: "metaDescmetaDesc",
    _id: "987",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "222",
  },
  {
    name: "Foo",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "baz",
    email: "metaDescmetaDesc",
    _id: "333",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "444",
  },
  {
    name: "Foo",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "baz",
    email: "metaDescmetaDesc",
    _id: "555",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "666",
  },
  {
    name: "Foo",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "baz",
    email: "metaDescmetaDesc",
    _id: "777",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "888",
  },
  {
    name: "Foo",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "baz",
    email: "metaDescmetaDesc",
    _id: "999",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "101010",
  },
  {
    name: "Foo",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "baz",
    email: "metaDescmetaDesc",
    _id: "111111",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "121212",
  },
  {
    name: "Foo",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "baz",
    email: "metaDescmetaDesc",
    _id: "131313",
  },
  {
    name: "Lorem",
    phone: "+91 4233434343",
    subject: "left",
    action: <IoCheckmarkDoneOutline className="mx-auto" />,
    status: "active",
    message: "dolor",
    email: "metaDescmetaDesc",
    _id: "141414",
  },
];
