import { IoCheckmarkDoneOutline } from "react-icons/io5";

export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "name",
    numeric: false,
    label: "Name",
  },
  {
    id: "designation",
    numeric: false,
    label: "Designation",
  },
  {
    id: "description",
    numeric: false,
    label: "Description",
  },
  {
    id: "facebook",
    numeric: false,
    label: "Facebook",
  },
  {
    id: "instagram",
    numeric: false,
    label: "Instagram",
  },
  {
    id: "twitter",
    numeric: false,
    label: "Twitter",
  },
  {
    id: "linkedin",
    numeric: false,
    label: "Linkedin",
  },
  {
    id: "status",
    numeric: false,
    label: "Status",
  },
  {
    id: "action",
    numeric: true,
    label: "ACTION",
  },
];

export const TableData = [
  {
    degination: "ABC",
    name: "left",
    experiance: "3+",
    description: "description",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "111",
  },
  {
    degination: "dd",
    name: "left",
    experiance: "3+",
    description: "eeee",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "987",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "222",
  },
  {
    degination: "Foo",
    name: "left",
    experiance: "3+",
    description: "baz",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "333",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "444",
  },
  {
    degination: "Foo",
    name: "left",
    experiance: "3+",
    description: "baz",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "555",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "666",
  },
  {
    degination: "Foo",
    name: "left",
    experiance: "3+",
    description: "baz",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "777",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "888",
  },
  {
    degination: "Foo",
    name: "left",
    experiance: "3+",
    description: "baz",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "999",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "101010",
  },
  {
    degination: "Foo",
    name: "left",
    experiance: "3+",
    description: "baz",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "111111",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "121212",
  },
  {
    degination: "Foo",
    name: "left",
    experiance: "3+",
    description: "baz",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "131313",
  },
  {
    degination: "Lorem",
    name: "left",
    experiance: "3+",
    description: "dolor",
    facebook: "rajsthan",
    instagram: "instagram",
    twitter: "metaDescmetaDesc",
    linkedin: "linkedin",
    status: "active",
    _id: "141414",
  },
];
