export default {
  postLogin: () => `auth/login`,
  postAddBlog: () => `blog/createBlog`,
  postUpdateBlog: () => `blog/updateBlog`,
  getAllBlogs: () => `blog/getAllBlog`,
  deleteBlog: () => `blog/deleteBlog`,
  postAddCareer: () => `career/createCareer`,
  getAllCareer: () => `career/getAllCareer`,
  postUpdateCareer: () => `career/updateCareer`,
  deleteCareer: () => `career/deleteCareer`,
  postAddAboutpage: () => `about/createAboutPage`,
  postUpdateAboutpage: () => `about/updateAboutPage`,
  getAllAboutpage: () => `about/getAboutPageList`,
  deleteAboutpage: () => `about/deleteAboutPageData`,
  postAddSlider: () => `slider/createSlider`,
  postUpdateSlider: () => `slider/updateSlider`,
  getAllSlider: () => `slider/getSliderList`,
  deleteSlider: () => `slider/deleteSliders`,
  // getUserToken:(id)=>`users/token/get?token=${id}`,
};
