export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "title",
    numeric: false,
    label: "Title",
  },
  {
    id: "metaTitle",
    numeric: false,
    label: "Meta title",
  },
  {
    id: "metaDesc",
    numeric: false,
    label: "Meta Description",
  },
  {
    id: "image_position",
    numeric: false,
    label: "Image Position",
  },
  {
    id: "action",
    numeric: true,
    label: "ACTION",
  },
];

export const TableData = [
  {
    title: "ABC",
    image_position: "left",
    metaTitle: "description",
    metaDesc: "metaDescmetaDesc",
    _id: "111",
  },
  {
    title: "dd",
    image_position: "left",
    metaTitle: "eeee",
    metaDesc: "metaDescmetaDesc",
    _id: "987",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "222",
  },
  {
    title: "Foo",
    image_position: "left",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "333",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "444",
  },
  {
    title: "Foo",
    image_position: "left",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "555",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "666",
  },
  {
    title: "Foo",
    image_position: "left",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "777",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "888",
  },
  {
    title: "Foo",
    image_position: "left",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "999",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "101010",
  },
  {
    title: "Foo",
    image_position: "left",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "111111",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "121212",
  },
  {
    title: "Foo",
    image_position: "left",
    metaTitle: "baz",
    metaDesc: "metaDescmetaDesc",
    _id: "131313",
  },
  {
    title: "Lorem",
    image_position: "left",
    metaTitle: "dolor",
    metaDesc: "metaDescmetaDesc",
    _id: "141414",
  },
];
