import { IoCheckmarkDoneOutline } from "react-icons/io5";

export const HeaderData = [
  {
    id: "no",
    numeric: true,
    label: "SR NO",
  },
  {
    id: "designation",
    numeric: false,
    label: "designation",
  },
  {
    id: "department",
    numeric: false,
    label: "Department",
  },
  {
    id: "description",
    numeric: false,
    label: "Description",
  },
  {
    id: "experiance",
    numeric: false,
    label: "Experiance",
  },
  {
    id: "location",
    numeric: false,
    label: "Location",
  },
  {
    id: "vacancy",
    numeric: false,
    label: "Vacancy",
  },
  {
    id: "active",
    numeric: false,
    label: "Active",
  },
  {
    id: "action",
    numeric: true,
    label: "ACTION",
  },
];

export const TableData = [
  {
    designation: "ABC",
    department: "left",
    experiance: "3+",
    description: "description",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "111",
  },
  {
    designation: "dd",
    department: "left",
    experiance: "3+",
    description: "eeee",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "987",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "222",
  },
  {
    designation: "Foo",
    department: "left",
    experiance: "3+",
    description: "baz",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "333",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "444",
  },
  {
    designation: "Foo",
    department: "left",
    experiance: "3+",
    description: "baz",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "555",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "666",
  },
  {
    designation: "Foo",
    department: "left",
    experiance: "3+",
    description: "baz",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "777",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "888",
  },
  {
    designation: "Foo",
    department: "left",
    experiance: "3+",
    description: "baz",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "999",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "101010",
  },
  {
    designation: "Foo",
    department: "left",
    experiance: "3+",
    description: "baz",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "111111",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "121212",
  },
  {
    designation: "Foo",
    department: "left",
    experiance: "3+",
    description: "baz",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "131313",
  },
  {
    designation: "Lorem",
    department: "left",
    experiance: "3+",
    description: "dolor",
    location: "rajsthan",
    vacancy: "metaDescmetaDesc",
    active: "active",
    _id: "141414",
  },
];
